# Markdownlint configuration
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Enable common sensible defaults; override a few rules for repo style.
MD013: # line-length
  line_length: 100
  code_block_line_length: 120
  heading_line_length: 100
MD024: # no-duplicate-heading
  siblings_only: true
MD033: false # allow inline HTML
MD041: false # first line in file should be a top-level heading
MD046: # fenced-code-blocks style
  style: fenced
