repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: detect-private-key
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args:
          - --disable
          - MD013  # line length
          - MD033  # inline HTML
          - MD041  # first line should be a heading
  - repo: local
    hooks:
      - id: ty
        name: ty type checker
        entry: uv run ty check .
        language: system
        pass_filenames: false
        types: [python]

ci:
  autofix_commit_msg: "chore(pre-commit): auto-fix issues"
  autofix_prs: true
  autofix_summary: true
  skip: []
