name: CI

on:
  # Avoid duplicate runs: run on PRs for branches, and on direct pushes to main
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    name: Test (uv + pytest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Install Python
        run: uv python install 3.11

      - name: Sync dependencies (dev)
        run: uv sync --all-extras --dev

      - name: Run tests with coverage
        run: uv run pytest -vv --cov=pocketsmith_mcp --cov-report=term-missing:skip-covered --cov-report=xml

      - name: Upload coverage.xml artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: unittests
          fail_ci_if_error: false
