name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    name: Test (uv + pytest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Install Python
        run: uv python install 3.11

      - name: Sync dependencies (dev)
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest -vv
