name: Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Install deps
        run: uv sync
      - name: Lint (ruff)
        run: uv run ruff check .
      - name: Type check (ty)
        run: uv run ty check .

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Semantic Release (noop)
        uses: python-semantic-release/python-semantic-release@v10.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          no_operation_mode: true  # dry-run for safety; flip to false to release
          # verbosity: 2
          # strict: true
