name: Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # full history for version calc
          fetch-tags: true # ensure tags are available
      - uses: astral-sh/setup-uv@v3
      - name: Install deps
        run: uv sync
      - name: Lint (ruff)
        run: uv run ruff check .
      - name: Type check (ty)
        run: uv run ty check .

  release:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: astral-sh/setup-uv@v3
      - name: Update lockfile
        run: uv lock
      - name: Semantic Release (noop)
        uses: python-semantic-release/python-semantic-release@v10.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"
          no_operation_mode: false  # enable real releases
          # verbosity: 2
          # strict: true
